[project]
name = "recipe-assistant-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ana Pinto", email = "anapinto2503@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "gradio>=6.29.0",
    "pydantic-ai",
    "pydantic-evals>=2.48.0",
    "python-dotenv",
]

[project.scripts]
recipe-assistant-ui = "recipe_assistant_ui:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
